### ISSUE TITLE
Baserow Fundamentals

### ISSUE THREAD

**Issue by widal001** [quillio-digital/common-tools#1]
### Description

Explore the core features of Baserow and document key takeaways

### TODO 

- [ ] Create and modify a table
- [ ] Create and modify a view
- [ ] Add a row

### Definition of Done

- [ ] Each of the features above have been tested via the UI and the API
- [ ] The code for the API calls is committed to a repository
- [ ] A GitBook page documenting key takeaways has been created
